<a href="https://colab.research.google.com/github/hmyrcmn/MachinaLearning/blob/main/dataPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
veriler = [
    ['tr', 130, 30, 10, 'e'],
    ['tr', 125, 36, 11, 'e'],
    ['tr', 135, 34, 10, 'k'],
    ['tr', 133, 30, 9, 'k'],
    ['tr', 129, 38, 12, 'e'],
    ['tr', 180, 90, 30, 'e'],
    ['tr', 190, 80, 25, 'e'],
    ['tr', 175, 90, 35, 'e'],
    ['tr', 177, 60, 22, 'k'],
    ['us', 185, 105, 33, 'e'],
    ['us', 165, 55, 27, 'k'],
    ['us', 155, 50, 44, 'k'],
    ['us', 160, 58, None, 'k'],
    ['us', 162, 59, 41, 'k'],
    ['us', 167, 62, 55, 'k'],
    ['fr', 174, 70, 47, 'e'],
    ['fr', 193, 90, None, 'e'],
    ['fr', 187, 80, 27, 'e'],
    ['fr', 183, 88, 28, 'e'],
    ['fr', 159, 40, 29, 'k'],
    ['fr', 164, 66, 32, 'k'],
    ['fr', 166, 56, 42, 'k']
]

# Verileri bir veri çerçevesine yükleyin
veri_cercevesi = pd.DataFrame(veriler, columns=['Ülke', 'Boy', 'Kilo', 'Yaş', 'Cinsiyet'])

# Veri çerçevesini gösterin
print(veri_cercevesi)
veri_cercevesi.to_csv('veriler.csv', index=False)



   Ülke  Boy  Kilo   Yaş Cinsiyet
0    tr  130    30  10.0        e
1    tr  125    36  11.0        e
2    tr  135    34  10.0        k
3    tr  133    30   9.0        k
4    tr  129    38  12.0        e
5    tr  180    90  30.0        e
6    tr  190    80  25.0        e
7    tr  175    90  35.0        e
8    tr  177    60  22.0        k
9    us  185   105  33.0        e
10   us  165    55  27.0        k
11   us  155    50  44.0        k
12   us  160    58   NaN        k
13   us  162    59  41.0        k
14   us  167    62  55.0        k
15   fr  174    70  47.0        e
16   fr  193    90   NaN        e
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k


In [23]:
data=pd.read_csv('veriler.csv')
data

Ülke  Boy  Kilo   Yaş Cinsiyet
0    tr  130    30  10.0        e
1    tr  125    36  11.0        e
2    tr  135    34  10.0        k
3    tr  133    30   9.0        k
4    tr  129    38  12.0        e
5    tr  180    90  30.0        e
6    tr  190    80  25.0        e
7    tr  175    90  35.0        e
8    tr  177    60  22.0        k
9    us  185   105  33.0        e
10   us  165    55  27.0        k
11   us  155    50  44.0        k
12   us  160    58   NaN        k
13   us  162    59  41.0        k
14   us  167    62  55.0        k
15   fr  174    70  47.0        e
16   fr  193    90   NaN        e
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k

In [16]:
data.head()
#verinin ilk 5 değeri


Ülke  Boy  Kilo   Yaş Cinsiyet
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k

In [17]:
data.tail()

Ülke  Boy  Kilo   Yaş Cinsiyet
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k

In [24]:
data.shape
#verinin boyutunun öğrenilmesi
# metadata (veriye ait veri )

(22, 5)

In [32]:
data['Boy']


0     130
1     125
2     135
3     133
4     129
5     180
6     190
7     175
8     177
9     185
10    165
11    155
12    160
13    162
14    167
15    174
16    193
17    187
18    183
19    159
20    164
21    166
Name: Boy, dtype: int64

In [33]:
data['Yaş']

0     10.0
1     11.0
2     10.0
3      9.0
4     12.0
5     30.0
6     25.0
7     35.0
8     22.0
9     33.0
10    27.0
11    44.0
12     NaN
13    41.0
14    55.0
15    47.0
16     NaN
17    27.0
18    28.0
19    29.0
20    32.0
21    42.0
Name: Yaş, dtype: float64

missing value

In [15]:
#veride null degerler varmı nasıl kodntrol edili
cauntNull=data.isnull().sum()
print(cauntNull)


Ülke        0
Boy         0
Kilo        0
Yaş         2
Cinsiyet    0
dtype: int64


In [38]:
from sklearn.impute import SimpleImputer
import numpy as np
imputer= SimpleImputer(missing_values=np.nan,strategy='mean')
Yas=data.iloc[:,1:4].values
print(Yas)

imputer =imputer.fit(Yas[:,1:4])
Yas[:,1:4]=imputer.transform(Yas[:,1:4])
print(Yas)

[[130.  30.  10.]
 [125.  36.  11.]
 [135.  34.  10.]
 [133.  30.   9.]
 [129.  38.  12.]
 [180.  90.  30.]
 [190.  80.  25.]
 [175.  90.  35.]
 [177.  60.  22.]
 [185. 105.  33.]
 [165.  55.  27.]
 [155.  50.  44.]
 [160.  58.  nan]
 [162.  59.  41.]
 [167.  62.  55.]
 [174.  70.  47.]
 [193.  90.  nan]
 [187.  80.  27.]
 [183.  88.  28.]
 [159.  40.  29.]
 [164.  66.  32.]
 [166.  56.  42.]]
[[130.    30.    10.  ]
 [125.    36.    11.  ]
 [135.    34.    10.  ]
 [133.    30.     9.  ]
 [129.    38.    12.  ]
 [180.    90.    30.  ]
 [190.    80.    25.  ]
 [175.    90.    35.  ]
 [177.    60.    22.  ]
 [185.   105.    33.  ]
 [165.    55.    27.  ]
 [155.    50.    44.  ]
 [160.    58.    28.45]
 [162.    59.    41.  ]
 [167.    62.    55.  ]
 [174.    70.    47.  ]
 [193.    90.    28.45]
 [187.    80.    27.  ]
 [183.    88.    28.  ]
 [159.    40.    29.  ]
 [164.    66.    32.  ]
 [166.    56.    42.  ]]


kategorik verileri  ülke tr fr us ın işlenebilecek formata dönüştüürlülmesi

In [68]:
country=data.iloc[:,0:1].values

print(country)

# caunty tr =1, us =2 fr=0 olrak düzenlendi
from sklearn import preprocessing
# LABEL ENCODER  SSAYISAL DEĞER VEİRRİ 0 1-2-3
le=preprocessing.LabelEncoder()
country[:,0]=le.fit_transform(data.iloc[:,0])
print(country)
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
#ohe = OneHotEncoder #use import with special library

# remember OneHotEncoder uding without ()
# ONE HOT ENCODER COLON BAŞLIKLARI İLE ATAMA YAPARAK COLONA AİDİYETİN 0 -1 İLE İFADE EDİLMESİNİ SAĞLAR :
# TR COLONUND VERİ 1 DEGERİ TAŞIYORSA O KİŞİ TR  O İSE TR DEĞİL FR YA DA US
ohe=preprocessing.OneHotEncoder

country = ohe.fit_transform(country).toarray()
print("One-Hot Encoded Ülke Dizisi:")
print(country)

[['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']]
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
One-Hot Encoded Ülke Dizisi:
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [77]:
#verirlerin birleştirilmesi
data
lastData=pd.DataFrame(data=country,index=range(22),columns=["fr","tr","us"])
lastData
# işlenmiş country verilier getirildi bunlar düzenlenmiş  dönüştürülmüş kategorik veriler


fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0

In [78]:
#YASDAKİ NULL DEGERLERİ DÜZENMENMİŞ VEİRLER
lastData2=pd.DataFrame(data=Yas,index=range(22),columns=["boy","kilo","yas"])
lastData2

boy   kilo    yas
0   130.0   30.0  10.00
1   125.0   36.0  11.00
2   135.0   34.0  10.00
3   133.0   30.0   9.00
4   129.0   38.0  12.00
5   180.0   90.0  30.00
6   190.0   80.0  25.00
7   175.0   90.0  35.00
8   177.0   60.0  22.00
9   185.0  105.0  33.00
10  165.0   55.0  27.00
11  155.0   50.0  44.00
12  160.0   58.0  28.45
13  162.0   59.0  41.00
14  167.0   62.0  55.00
15  174.0   70.0  47.00
16  193.0   90.0  28.45
17  187.0   80.0  27.00
18  183.0   88.0  28.00
19  159.0   40.0  29.00
20  164.0   66.0  32.00
21  166.0   56.0  42.00

In [87]:
gender=data.iloc[:,4].values
gender

lastData3=pd.DataFrame(data=gender,index=range(22),columns=["gender"])
lastData3


gender
0       e
1       e
2       k
3       k
4       e
5       e
6       e
7       e
8       k
9       e
10      k
11      k
12      k
13      k
14      k
15      e
16      e
17      e
18      e
19      k
20      k
21      k

In [104]:
#verilerin birleştirilmesi
#axis=1 ile düzgün eşleşme sağlandı
data=pd.concat([lastData,lastData2,lastData3],axis=1)
data

s=pd.concat([lastData,lastData2],axis=1)
s


fr   tr   us    boy   kilo    yas
0   0.0  1.0  0.0  130.0   30.0  10.00
1   0.0  1.0  0.0  125.0   36.0  11.00
2   0.0  1.0  0.0  135.0   34.0  10.00
3   0.0  1.0  0.0  133.0   30.0   9.00
4   0.0  1.0  0.0  129.0   38.0  12.00
5   0.0  1.0  0.0  180.0   90.0  30.00
6   0.0  1.0  0.0  190.0   80.0  25.00
7   0.0  1.0  0.0  175.0   90.0  35.00
8   0.0  1.0  0.0  177.0   60.0  22.00
9   0.0  0.0  1.0  185.0  105.0  33.00
10  0.0  0.0  1.0  165.0   55.0  27.00
11  0.0  0.0  1.0  155.0   50.0  44.00
12  0.0  0.0  1.0  160.0   58.0  28.45
13  0.0  0.0  1.0  162.0   59.0  41.00
14  0.0  0.0  1.0  167.0   62.0  55.00
15  1.0  0.0  0.0  174.0   70.0  47.00
16  1.0  0.0  0.0  193.0   90.0  28.45
17  1.0  0.0  0.0  187.0   80.0  27.00
18  1.0  0.0  0.0  183.0   88.0  28.00
19  1.0  0.0  0.0  159.0   40.0  29.00
20  1.0  0.0  0.0  164.0   66.0  32.00
21  1.0  0.0  0.0  166.0   56.0  42.00

In [105]:
s2=pd.concat([s,lastData3],axis=1)
s2

fr   tr   us    boy   kilo    yas gender
0   0.0  1.0  0.0  130.0   30.0  10.00      e
1   0.0  1.0  0.0  125.0   36.0  11.00      e
2   0.0  1.0  0.0  135.0   34.0  10.00      k
3   0.0  1.0  0.0  133.0   30.0   9.00      k
4   0.0  1.0  0.0  129.0   38.0  12.00      e
5   0.0  1.0  0.0  180.0   90.0  30.00      e
6   0.0  1.0  0.0  190.0   80.0  25.00      e
7   0.0  1.0  0.0  175.0   90.0  35.00      e
8   0.0  1.0  0.0  177.0   60.0  22.00      k
9   0.0  0.0  1.0  185.0  105.0  33.00      e
10  0.0  0.0  1.0  165.0   55.0  27.00      k
11  0.0  0.0  1.0  155.0   50.0  44.00      k
12  0.0  0.0  1.0  160.0   58.0  28.45      k
13  0.0  0.0  1.0  162.0   59.0  41.00      k
14  0.0  0.0  1.0  167.0   62.0  55.00      k
15  1.0  0.0  0.0  174.0   70.0  47.00      e
16  1.0  0.0  0.0  193.0   90.0  28.45      e
17  1.0  0.0  0.0  187.0   80.0  27.00      e
18  1.0  0.0  0.0  183.0   88.0  28.00      e
19  1.0  0.0  0.0  159.0   40.0  29.00      k
20  1.0  0.0  0.0  164.0   66.0  32.00      k
21  1.0  0.0  0.0  166.0   56.0  42.00      k

In [106]:
#eğitim ve test verilerinin oluştrulması
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(s,lastData3,test_size=0.33,random_state=0)

x_train


fr   tr   us    boy   kilo    yas
8   0.0  1.0  0.0  177.0   60.0  22.00
6   0.0  1.0  0.0  190.0   80.0  25.00
16  1.0  0.0  0.0  193.0   90.0  28.45
4   0.0  1.0  0.0  129.0   38.0  12.00
2   0.0  1.0  0.0  135.0   34.0  10.00
5   0.0  1.0  0.0  180.0   90.0  30.00
17  1.0  0.0  0.0  187.0   80.0  27.00
9   0.0  0.0  1.0  185.0  105.0  33.00
7   0.0  1.0  0.0  175.0   90.0  35.00
18  1.0  0.0  0.0  183.0   88.0  28.00
3   0.0  1.0  0.0  133.0   30.0   9.00
0   0.0  1.0  0.0  130.0   30.0  10.00
15  1.0  0.0  0.0  174.0   70.0  47.00
12  0.0  0.0  1.0  160.0   58.0  28.45

In [100]:
x_test

fr   tr   us    boy  kilo   yas
20  1.0  0.0  0.0  164.0  66.0  32.0
10  0.0  0.0  1.0  165.0  55.0  27.0
14  0.0  0.0  1.0  167.0  62.0  55.0
13  0.0  0.0  1.0  162.0  59.0  41.0
1   0.0  1.0  0.0  125.0  36.0  11.0
21  1.0  0.0  0.0  166.0  56.0  42.0
11  0.0  0.0  1.0  155.0  50.0  44.0
19  1.0  0.0  0.0  159.0  40.0  29.0

In [101]:
y_train

gender
8       k
6       e
16      e
4       e
2       k
5       e
17      e
9       e
7       e
18      e
3       k
0       e
15      e
12      k

In [103]:
y_test

gender
20      k
10      k
14      k
13      k
1       e
21      k
11      k
19      k

ÖZNİTEKİL ÖLÇEKLEME

In [110]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train=sc.fit_transform(x_train)
X_test=sc.fit_transform(x_test)
X_train


array([[ 1.29099445, -0.37796447, -1.        ,  0.47240026,  1.32853794,
        -0.24991255],
       [-0.77459667, -0.37796447,  1.        ,  0.54952683,  0.20439045,
        -0.64977262],
       [-0.77459667, -0.37796447,  1.        ,  0.70377998,  0.91975703,
         1.58944379],
       [-0.77459667, -0.37796447,  1.        ,  0.31814711,  0.61317136,
         0.46983559],
       [-0.77459667,  2.64575131, -1.        , -2.53553608, -1.73731884,
        -1.92932485],
       [ 1.29099445, -0.37796447, -1.        ,  0.6266534 ,  0.30658568,
         0.5498076 ],
       [-0.77459667, -0.37796447,  1.        , -0.2217389 , -0.30658568,
         0.70975163],
       [ 1.29099445, -0.37796447, -1.        ,  0.08676739, -1.32853794,
        -0.48982859]])

In [111]:
X_test

array([[ 1.29099445, -0.37796447, -1.        ,  0.47240026,  1.32853794,
        -0.24991255],
       [-0.77459667, -0.37796447,  1.        ,  0.54952683,  0.20439045,
        -0.64977262],
       [-0.77459667, -0.37796447,  1.        ,  0.70377998,  0.91975703,
         1.58944379],
       [-0.77459667, -0.37796447,  1.        ,  0.31814711,  0.61317136,
         0.46983559],
       [-0.77459667,  2.64575131, -1.        , -2.53553608, -1.73731884,
        -1.92932485],
       [ 1.29099445, -0.37796447, -1.        ,  0.6266534 ,  0.30658568,
         0.5498076 ],
       [-0.77459667, -0.37796447,  1.        , -0.2217389 , -0.30658568,
         0.70975163],
       [ 1.29099445, -0.37796447, -1.        ,  0.08676739, -1.32853794,
        -0.48982859]])