<a href="https://colab.research.google.com/github/hmyrcmn/MachinaLearning/blob/main/MultipleLinearGergesion_ODEV_BackelimininationWithPvalue.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1646]:
import pandas as pd

# Veri setinizi oluşturun
data = {
    'outlook': ['sunny', 'sunny', 'overcast', 'rainy', 'rainy', 'rainy', 'overcast', 'sunny', 'sunny', 'rainy', 'sunny', 'overcast', 'overcast', 'rainy'],
    'temperature': [85, 80, 83, 70, 68, 65, 64, 72, 69, 75, 75, 72, 81, 71],
    'humidity': [85, 90, 86, 96, 80, 70, 65, 95, 70, 80, 70, 90, 75, 91],
    'windy': [False, True, False, False, False, True, True, False, False, False, True, True, False, True],
    'play': ['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'no']
}

# Veri setini bir veri çerçevesine dönüştürün
df = pd.DataFrame(data)

# Veriyi CSV dosyasına kaydet
df.to_csv('tenis.csv', index=False)
data=pd.read_csv('tenis.csv')
data



outlook  temperature  humidity  windy play
0      sunny           85        85  False   no
1      sunny           80        90   True   no
2   overcast           83        86  False  yes
3      rainy           70        96  False  yes
4      rainy           68        80  False  yes
5      rainy           65        70   True   no
6   overcast           64        65   True  yes
7      sunny           72        95  False   no
8      sunny           69        70  False  yes
9      rainy           75        80  False  yes
10     sunny           75        70   True  yes
11  overcast           72        90   True  yes
12  overcast           81        75  False  yes
13     rainy           71        91   True   no

In [1647]:
#veride null degerler varmı nasıl kodntrol edili
cauntNull=data.isnull().sum()
print(cauntNull)
# veri seti null değer içermiyor


outlook        0
temperature    0
humidity       0
windy          0
play           0
dtype: int64


play cloumns converted the numeric data

In [1648]:
# label encoding for  play and windy  0/1 den biir olarka atamaların yapılması
play=data.iloc[:,-1:].values
play


array([['no'],
       ['no'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['no'],
       ['yes'],
       ['no'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['no']], dtype=object)

In [1649]:
 # play columns  alındı
from sklearn import preprocessing

le_play=preprocessing.LabelEncoder()
play[:,-1]=le_play.fit_transform(data.iloc[:,-1])
play

# no=0 yes=1

array([[0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0]], dtype=object)

In [1650]:
# label encoding for  windy  0/1 den biir olarka atamaların yapılması
windy=data.iloc[:,-2:-1].values # selected windy column
windy


array([[False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True]])

deneme kısa yol :


In [1651]:
# shortway tidy
data2=data.apply(preprocessing.LabelEncoder().fit_transform)
data2

outlook  temperature  humidity  windy  play
0         2           11         4      0     0
1         2            8         6      1     0
2         0           10         5      0     1
3         1            4         9      0     1
4         1            2         3      0     1
5         1            1         1      1     0
6         0            0         0      1     1
7         2            6         8      0     0
8         2            3         1      0     1
9         1            7         3      0     1
10        2            7         1      1     1
11        0            6         6      1     1
12        0            9         2      0     1
13        1            5         7      1     0

In [1652]:
c=data2.iloc[:,:1]
c
from sklearn import preprocessing
ohe=preprocessing.OneHotEncoder()
c=ohe.fit_transform(c).toarray()
c

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

KISAYOL BİTİŞ

In [1653]:
df = pd.DataFrame(data)
le = preprocessing.LabelEncoder()
df['windy'] = le.fit_transform(df['windy'])
df['play']=le.fit_transform(data.iloc[:,-1])

df

# data tidy true=1 yes=1 and false=0 no=0 in play and windy column in data

outlook  temperature  humidity  windy  play
0      sunny           85        85      0     0
1      sunny           80        90      1     0
2   overcast           83        86      0     1
3      rainy           70        96      0     1
4      rainy           68        80      0     1
5      rainy           65        70      1     0
6   overcast           64        65      1     1
7      sunny           72        95      0     0
8      sunny           69        70      0     1
9      rainy           75        80      0     1
10     sunny           75        70      1     1
11  overcast           72        90      1     1
12  overcast           81        75      0     1
13     rainy           71        91      1     0

In [1654]:
#one hot encoding işlemi
df_OneEncoded = pd.get_dummies(df, columns=['outlook'])
data=df_OneEncoded
data

temperature  humidity  windy  play  outlook_overcast  outlook_rainy  \
0            85        85      0     0                 0              0   
1            80        90      1     0                 0              0   
2            83        86      0     1                 1              0   
3            70        96      0     1                 0              1   
4            68        80      0     1                 0              1   
5            65        70      1     0                 0              1   
6            64        65      1     1                 1              0   
7            72        95      0     0                 0              0   
8            69        70      0     1                 0              0   
9            75        80      0     1                 0              1   
10           75        70      1     1                 0              0   
11           72        90      1     1                 1              0   
12           81        75      0     1                 1              0   
13           71        91      1     0                 0              1   

    outlook_sunny  
0               1  
1               1  
2               0  
3               0  
4               0  
5               0  
6               0  
7               1  
8               1  
9               0  
10              1  
11              0  
12              0  
13              0

In [1655]:
from sklearn.model_selection import train_test_split

# Verileri eğitim ve test setlerine ayırma
x_train, x_test, y_train, y_test = train_test_split( data.drop(columns=['humidity']), data['humidity'], test_size=0.33, random_state=0)
x_train

temperature  windy  play  outlook_overcast  outlook_rainy  outlook_sunny
13           71      1     0                 0              1              0
9            75      0     1                 0              1              0
1            80      1     0                 0              0              1
7            72      0     0                 0              0              1
10           75      1     1                 0              0              1
3            70      0     1                 0              1              0
0            85      0     0                 0              0              1
5            65      1     0                 0              1              0
12           81      0     1                 1              0              0

In [1656]:
x_test

temperature  windy  play  outlook_overcast  outlook_rainy  outlook_sunny
8            69      0     1                 0              0              1
6            64      1     1                 1              0              0
4            68      0     1                 0              1              0
11           72      1     1                 1              0              0
2            83      0     1                 1              0              0

In [1657]:
y_train



13    91
9     80
1     90
7     95
10    70
3     96
0     85
5     70
12    75
Name: humidity, dtype: int64

In [1658]:
y_test

8     70
6     65
4     80
11    90
2     86
Name: humidity, dtype: int64

In [1659]:
from sklearn.linear_model import LinearRegression

# Doğrusal regresyon modelini oluşturun
regressor = LinearRegression()

# Eğitim verilerinizi ve hedef değişkeninizi belirtin, bu verilerle modeli eğitin
regressor.fit(x_train, y_train)  # x_train: bağımsız değişkenler, y_train: hedef değişken


LinearRegression()

In [1660]:
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [1661]:
y_pred=regressor.predict(x_test)
y_pred


array([84.45365573, 63.93839954, 85.76050662, 64.21013241, 75.06793322])

In [1662]:
y_test

8     70
6     65
4     80
11    90
2     86
Name: humidity, dtype: int64

In [1663]:
data

temperature  humidity  windy  play  outlook_overcast  outlook_rainy  \
0            85        85      0     0                 0              0   
1            80        90      1     0                 0              0   
2            83        86      0     1                 1              0   
3            70        96      0     1                 0              1   
4            68        80      0     1                 0              1   
5            65        70      1     0                 0              1   
6            64        65      1     1                 1              0   
7            72        95      0     0                 0              0   
8            69        70      0     1                 0              0   
9            75        80      0     1                 0              1   
10           75        70      1     1                 0              0   
11           72        90      1     1                 1              0   
12           81        75      0     1                 1              0   
13           71        91      1     0                 0              1   

    outlook_sunny  
0               1  
1               1  
2               0  
3               0  
4               0  
5               0  
6               0  
7               1  
8               1  
9               0  
10              1  
11              0  
12              0  
13              0

In [1664]:
data = data[['windy', 'play', 'outlook_overcast', 'outlook_rainy', 'outlook_sunny','temperature','humidity']]
data

windy  play  outlook_overcast  outlook_rainy  outlook_sunny  temperature  \
0       0     0                 0              0              1           85   
1       1     0                 0              0              1           80   
2       0     1                 1              0              0           83   
3       0     1                 0              1              0           70   
4       0     1                 0              1              0           68   
5       1     0                 0              1              0           65   
6       1     1                 1              0              0           64   
7       0     0                 0              0              1           72   
8       0     1                 0              0              1           69   
9       0     1                 0              1              0           75   
10      1     1                 0              0              1           75   
11      1     1                 1              0              0           72   
12      0     1                 1              0              0           81   
13      1     0                 0              1              0           71   

    humidity  
0         85  
1         90  
2         86  
3         96  
4         80  
5         70  
6         65  
7         95  
8         70  
9         80  
10        70  
11        90  
12        75  
13        91

In [1665]:
#bacward elimination  : en yükseği elenerek işlem yapılır
# calculate the p value

import statsmodels.api as sm
import numpy as np

# değişkenlerden hangisinin etkisi fazla? array a eklenir
# humidity dışındkai sutunları alır
x=np.append(arr=np.ones((14,1)).astype(int),values=data.iloc[:,:-1],axis=1)

# değişkenlerden hangisinin etkisi fazla? array a eklenir

X_l= data.iloc[:,[0,1,2,3,4,5]].values # 6 kolonu al sonrasında elimine işlemi yapılacal p value degeri hesaplanacak
model=sm.OLS(data.iloc[:,-1:],X_l).fit() # regresyon sonucu = isttaistiksel sonuçları çıkartmayı sağlıyor : boy bağımsız değişkenlerden ne kadar etkiledniyor
model.summary()


/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:               humidity   R-squared:                       0.294
Model:                            OLS   Adj. R-squared:                 -0.148
Method:                 Least Squares   F-statistic:                    0.6653
Date:                Mon, 09 Oct 2023   Prob (F-statistic):              0.661
Time:                        13:17:36   Log-Likelihood:                -49.542
No. Observations:                  14   AIC:                             111.1
Df Residuals:                       8   BIC:                             114.9
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -4.0286      7.229     -0.557      0.593     -20.698      12.641
x2            -8.2778      8.029     -1.031      0.333     -26.793      10.237
x3            52.3891     50.214      1.043      0.327     -63.404     168.183
x4            55.6337     45.233      1.230      0.254     -48.673     159.940
x5            49.4291     48.337      1.023      0.336     -62.035     160.893
x6             0.4920      0.597      0.825      0.433      -0.884       1.868
==============================================================================
Omnibus:                        0.935   Durbin-Watson:                   2.416
Prob(Omnibus):                  0.627   Jarque-Bera (JB):                0.823
Skew:                           0.389   Prob(JB):                        0.663
Kurtosis:                       2.103   Cond. No.                     2.08e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.08e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [1666]:
# x1 elimine edilir : windy elendi
data=data.iloc[:,1:]
data

play  outlook_overcast  outlook_rainy  outlook_sunny  temperature  \
0      0                 0              0              1           85   
1      0                 0              0              1           80   
2      1                 1              0              0           83   
3      1                 0              1              0           70   
4      1                 0              1              0           68   
5      0                 0              1              0           65   
6      1                 1              0              0           64   
7      0                 0              0              1           72   
8      1                 0              0              1           69   
9      1                 0              1              0           75   
10     1                 0              0              1           75   
11     1                 1              0              0           72   
12     1                 1              0              0           81   
13     0                 0              1              0           71   

    humidity  
0         85  
1         90  
2         86  
3         96  
4         80  
5         70  
6         65  
7         95  
8         70  
9         80  
10        70  
11        90  
12        75  
13        91

In [1667]:
X_l= data.iloc[:,[0,1,2,3,4]].values # 6 kolonu al sonrasında elimine işlemi yapılacal p value degeri hesaplanacak
model=sm.OLS(data.iloc[:,-1:],X_l).fit() # regresyon sonucu = isttaistiksel sonuçları çıkartmayı sağlıyor : boy bağımsız değişkenlerden ne kadar etkiledniyor
model.summary()

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:               humidity   R-squared:                       0.266
Model:                            OLS   Adj. R-squared:                 -0.060
Method:                 Least Squares   F-statistic:                    0.8165
Date:                Mon, 09 Oct 2023   Prob (F-statistic):              0.546
Time:                        13:17:36   Log-Likelihood:                -49.809
No. Observations:                  14   AIC:                             109.6
Df Residuals:                       9   BIC:                             112.8
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -6.2865      6.909     -0.910      0.387     -21.916       9.343
x2            36.6564     39.905      0.919      0.382     -53.615     126.927
x3            41.9135     36.464      1.149      0.280     -40.573     124.400
x4            35.1064     39.339      0.892      0.395     -53.884     124.097
x5             0.6484      0.506      1.282      0.232      -0.496       1.793
==============================================================================
Omnibus:                        0.887   Durbin-Watson:                   2.360
Prob(Omnibus):                  0.642   Jarque-Bera (JB):                0.810
Skew:                           0.424   Prob(JB):                        0.667
Kurtosis:                       2.181   Cond. No.                     1.73e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.73e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [1668]:
x_train =x_train[['windy', 'play', 'outlook_overcast', 'outlook_rainy', 'outlook_sunny','temperature']]
x_train

windy  play  outlook_overcast  outlook_rainy  outlook_sunny  temperature
13      1     0                 0              1              0           71
9       0     1                 0              1              0           75
1       1     0                 0              0              1           80
7       0     0                 0              0              1           72
10      1     1                 0              0              1           75
3       0     1                 0              1              0           70
0       0     0                 0              0              1           85
5       1     0                 0              1              0           65
12      0     1                 1              0              0           81

In [1669]:
x_train=x_train.iloc[:,1:] # 1. sutundan ititbaren sutunları al windy gitti
x_train

play  outlook_overcast  outlook_rainy  outlook_sunny  temperature
13     0                 0              1              0           71
9      1                 0              1              0           75
1      0                 0              0              1           80
7      0                 0              0              1           72
10     1                 0              0              1           75
3      1                 0              1              0           70
0      0                 0              0              1           85
5      0                 0              1              0           65
12     1                 1              0              0           81

In [1670]:
x_test =x_test[['windy', 'play', 'outlook_overcast', 'outlook_rainy', 'outlook_sunny','temperature']]
x_test

windy  play  outlook_overcast  outlook_rainy  outlook_sunny  temperature
8       0     1                 0              0              1           69
6       1     1                 1              0              0           64
4       0     1                 0              1              0           68
11      1     1                 1              0              0           72
2       0     1                 1              0              0           83

In [1671]:
x_test=x_test.iloc[:,1:] # 1. sutundan ititbaren sutunları al windy gitti
x_test

play  outlook_overcast  outlook_rainy  outlook_sunny  temperature
8      1                 0              0              1           69
6      1                 1              0              0           64
4      1                 0              1              0           68
11     1                 1              0              0           72
2      1                 1              0              0           83

In [1672]:
y_test

8     70
6     65
4     80
11    90
2     86
Name: humidity, dtype: int64

In [1673]:
y_pred # eski tahmin değerlerimiz

array([84.45365573, 63.93839954, 85.76050662, 64.21013241, 75.06793322])

In [1674]:
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)
y_pred=regressor.predict(x_test)
y_pred # yeni tahmin degerlerimiz daha iyi tahmin edilmil t_test degerlerine daha yakın

array([77.98135142, 68.29304916, 81.05037539, 71.44926132, 75.78905304])

In [1675]:
# x1 elimine edilir : play elendi
data=data.iloc[:,1:]
data

outlook_overcast  outlook_rainy  outlook_sunny  temperature  humidity
0                  0              0              1           85        85
1                  0              0              1           80        90
2                  1              0              0           83        86
3                  0              1              0           70        96
4                  0              1              0           68        80
5                  0              1              0           65        70
6                  1              0              0           64        65
7                  0              0              1           72        95
8                  0              0              1           69        70
9                  0              1              0           75        80
10                 0              0              1           75        70
11                 1              0              0           72        90
12                 1              0              0           81        75
13                 0              1              0           71        91

In [1676]:
# katman 2 elimine
X_l= data.iloc[:,[0,1,2,3]].values # 6 kolonu al sonrasında elimine işlemi yapılacal p value degeri hesaplanacak
model=sm.OLS(data.iloc[:,-1:],X_l).fit() # regresyon sonucu = isttaistiksel sonuçları çıkartmayı sağlıyor : boy bağımsız değişkenlerden ne kadar etkiledniyor
model.summary()

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:               humidity   R-squared:                       0.199
Model:                            OLS   Adj. R-squared:                 -0.042
Method:                 Least Squares   F-statistic:                    0.8270
Date:                Mon, 09 Oct 2023   Prob (F-statistic):              0.509
Time:                        13:17:36   Log-Likelihood:                -50.425
No. Observations:                  14   AIC:                             108.8
Df Residuals:                      10   BIC:                             111.4
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            25.3137     37.580      0.674      0.516     -58.419     109.047
x2            33.4359     34.948      0.957      0.361     -44.434     111.306
x3            27.4547     38.097      0.721      0.488     -57.431     112.341
x4             0.7158      0.496      1.443      0.180      -0.390       1.821
==============================================================================
Omnibus:                        2.349   Durbin-Watson:                   2.548
Prob(Omnibus):                  0.309   Jarque-Bera (JB):                1.375
Skew:                           0.497   Prob(JB):                        0.503
Kurtosis:                       1.831   Cond. No.                     1.67e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.67e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

DAHA DA YÜKSELDİ P VALUE LAR DOLAYISIYLA ELİMİNE YAPILMADI MODEL DE